# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-27 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160622_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='附件名')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('download_times', models.PositiveIntegerField(default=0, verbose_name='下载次数')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='attachment',
            field=models.ManyToManyField(to='blog.Attachment', verbose_name='附件名'),
        ),
    ]
