# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-04 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161227_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-last_modified_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': '附件', 'verbose_name_plural': '附件'},
        ),
        migrations.AddField(
            model_name='article',
            name='en_keywords',
            field=models.CharField(blank=True, help_text='关键字之间以英文逗号（,）分隔', max_length=100, verbose_name='关键字'),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, help_text='关键字之间以逗号（，）分隔', max_length=100, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(blank=True, help_text='可选，如若为空将摘取正文的前1000个字符', max_length=1000, null=True, verbose_name='摘要'),
        ),
    ]
