# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-05 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170104_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='attachment',
        ),
        migrations.AddField(
            model_name='article',
            name='attachment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Attachment', verbose_name='附件名'),
            preserve_default=False,
        ),
    ]
