# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170105_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='attachment',
        ),
        migrations.AddField(
            model_name='article',
            name='attachment',
            field=models.ManyToManyField(to='blog.Attachment', verbose_name='附件名'),
        ),
    ]
